# Generated by Django 3.1 on 2021-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimtracker', '0004_auto_20210524_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
