# Generated by Django 3.1 on 2021-05-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimtracker', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='blocked_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vessel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimtracker.city')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='dest_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zimtracker.port'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ports',
            field=models.ManyToManyField(blank=True, to='zimtracker.Port'),
        ),
    ]
