# Generated by Django 3.1 on 2021-05-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zimtracker', '0007_auto_20210531_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='dest_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zimtracker.port'),
        ),
    ]
